attempt BinaryGibbsMetropolis
gives error

ERROR (theano.gof.opt): Optimization failure due to: local_greedy_distributor
ERROR (theano.gof.opt): node: Elemwise{mul}(Elemwise{mul}.0, repro_active_2007)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/Users/eddericugaddan/miniconda3/envs/mics-whales/lib/python3.7/site-packages/theano/gof/opt.py", line 2034, in process_node
    replacements = lopt.transform(node)
  File "/Users/eddericugaddan/miniconda3/envs/mics-whales/lib/python3.7/site-packages/theano/tensor/opt.py", line 6468, in local_greedy_distributor
    candidate, num, denum, out_type,)
  File "/Users/eddericugaddan/miniconda3/envs/mics-whales/lib/python3.7/site-packages/theano/tensor/opt.py", line 6423, in attempt_distribution
    neg_pairs))), num, denum
  File "/Users/eddericugaddan/miniconda3/envs/mics-whales/lib/python3.7/site-packages/theano/tensor/opt.py", line 4796, in merge_num_denum
    self.merge_num_denum(denum, []))
  File "/Users/eddericugaddan/miniconda3/envs/mics-whales/lib/python3.7/site-packages/theano/gof/op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "/Users/eddericugaddan/miniconda3/envs/mics-whales/lib/python3.7/site-packages/theano/tensor/elemwise.py", line 482, in make_node
    DimShuffle, *inputs)
  File "/Users/eddericugaddan/miniconda3/envs/mics-whales/lib/python3.7/site-packages/theano/tensor/elemwise.py", line 424, in get_output_info
    for i in inputs])
  File "/Users/eddericugaddan/miniconda3/envs/mics-whales/lib/python3.7/site-packages/theano/scalar/basic.py", line 1044, in make_node
    for input in inputs])]
  File "/Users/eddericugaddan/miniconda3/envs/mics-whales/lib/python3.7/site-packages/theano/scalar/basic.py", line 1052, in output_types
    variables = self.output_types_preference(*types)
  File "/Users/eddericugaddan/miniconda3/envs/mics-whales/lib/python3.7/site-packages/theano/scalar/basic.py", line 845, in upcast_out_nobool
    raise TypeError("bool output not supported")
TypeError: bool output not supported